# Generated by Django 5.1.2 on 2024-12-04 19:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PrayerCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.person')),
            ],
        ),
        migrations.CreateModel(
            name='PrayerDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('participants', models.ManyToManyField(through='calendar_app.PrayerCompletion', to='calendar_app.person')),
            ],
        ),
        migrations.AddField(
            model_name='prayercompletion',
            name='prayer_day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.prayerday'),
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('color', models.CharField(default='yellow', max_length=20)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='calendar_app.person')),
            ],
        ),
    ]
